# -*- coding: utf-8 -*-
"""JD-Parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkrTj5o5x4u3Iho5mEmxiHo3xT7SY9PH
"""

# STEP 1: Install dependencies
!pip install openai pandas

# STEP 2: Imports
import pandas as pd
import json
from openai import OpenAI

from httpx import Client
# STEP 3: Setup API
import os

os.environ["OPENAI_API_KEY"] = "Enter_Your_API_KEY"


client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

from google.colab import files
uploaded = files.upload()

# Get filename
filename = list(uploaded.keys())[0]

# Read CSV
df_input = pd.read_csv(filename)

# Extract job descriptions column
job_descriptions = df_input['Job_descriptions'].dropna().tolist()

print(f"✅ Loaded {len(job_descriptions)} job descriptions")

# STEP 5: EXTRACTION FUNCTION
def extract_job_data(text):
    prompt = f"""
    Extract structured information from the job description.

    Return ONLY valid JSON with:
    - role
    - seniority
    - experience
    - skills (list)
    - location
    - salary

    If any field is missing, return "Not specified".

    Job Description:
    {text}
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    return response.choices[0].message.content

# STEP 6: RUN PIPELINE
structured_data = []

for i, jd in enumerate(job_descriptions):
    try:
        result = extract_job_data(jd)

        # Clean response (important for JSON parsing)
        result = result.strip().replace("```json", "").replace("```", "")

        parsed = json.loads(result)
        structured_data.append(parsed)

        print(f"Processed {i+1}/{len(job_descriptions)}")

    except Exception as e:
        print(f"❌ Error at {i}: {e}")

        structured_data.append({
            "role": "Error",
            "seniority": "Error",
            "experience": "Error",
            "skills": [],
            "location": "Error",
            "salary": "Error"
        })

# STEP 7: CREATE DATAFRAME
df_output = pd.DataFrame(structured_data)

# STEP 8: SAVE OUTPUT CSV
df_output.to_csv("structured_jobs.csv", index=False)

print("\n✅ CSV file 'structured_jobs.csv' created successfully!")

# STEP 9: BONUS — SAVE RAW + STRUCTURED TOGETHER (VERY IMPRESSIVE)
df_final = pd.DataFrame({
    "raw_job_description": job_descriptions,
    "structured_output": structured_data
})

df_final.to_csv("final_output_with_raw.csv", index=False)

# Preview
df_output.head()

